name: mlops-example-tensorflow-regression
on: [push]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: 'Train my model'
        run: |
          python model.py
          
      - name: 'Setup CML'
        uses: iterative/setup-cml@v1
        
      - name: 'Generate CML report'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo -e "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          # Use inline image syntax
          echo "![](./model_results.png)" >> report.md
          
          # Use newer command
          cml comment create report.md
