name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: 'Train my model'
        run: |
          python model.py
          
      - name: 'Create CML report'
        uses: iterative/cml-action@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo -e "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
